baseurl      = "localhost"
title        = "DaniBell"
languageCode = "en-us"
theme        = "hello-friend-ng"
[pagination]
pagerSize = 10

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  enableThemeToggle = true
  homeSubtitle = "enjoy your stay :)"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Daniel's website"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[languages]
  [languages.en]
    title = "Hi, I'm Daniel."

    [languages.en.params]
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "/home/daniel"
      logoHomeLink = "/"
      logoCursorColor    = "#ff8000"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [params.portrait]
      path     = "/images/portrait.png"
      alt      = "Portrait"
      maxWidth = "100px"

  [params.footer]
    trademark = 2024
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Made by <a href=\"https://github.com/Danilol69\">DaniBell</a>",
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
    ]

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Social icons
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  [[params.social]]
    name = "email"
    url  = "mailto:danielbutbusiness@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/Danilol69"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/DaniBell1234"

  [[params.social]]
    name = "discord"
    url  = "https://discordapp.com/users/673143458671886336"

  [[params.social]]
    name = "spotify"
    url  = "https://open.spotify.com/user/31oh4uyfvvfoqe3fosqwz3vvenky?si=369c632ca714482f"

  # Header buttons
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

    [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"

    [[menu.main]]
    identifier = "uses"
    name       = "Uses"
    url        = "/uses"